### ISSUE TITLE
Report of the drag and drop not working

### ISSUE THREAD

**Issue by parallelus** [parallelus/Admin-Menu-Editor-for-Runway#3]
We may need to update the references to jQuery drag and drop for the latest version of WP. We have a report of it not working in this topic: http://runwaywp.com/support/topic/dont-work-at-all/

**Comment by lesninsky** [comment]
On my side drag and drop are working properly (WP 4.3.1). 
Depending on the image seems that default admin menu has not worked properly for user at all. Because for proper work at last one menu item is needed, I have added the functionality which adds spacer if default admin menu is missed.
